### ISSUE TITLE
ParseFoo should return an error

### ISSUE THREAD

**Issue by natefinch** [abice/go-enum#1]
ParseColor("chartreuse") returns Black.. that's not good.  You *could* start the enum with like ColorNone, but that's ugly.  Better to just have ParseColor return (Color, error).

**Comment by abice** [comment]
Yeah, I agree, thought of that just this morning, but haven't changed it yet.

Thanks!

**Comment by abice** [comment]
Just got it updated with an error return.  I'm gonna close this, but if you disagree with how I did it, just let me know.

Thanks for the feedback!
