### ISSUE TITLE
 questions about empty strings

### ISSUE THREAD

**Issue by liuzh825** [abice/go-enum#114]
Two questions about empty strings:

1. Enumeration values currently do not support empty strings? (because there is a valid empty string case)
2. The mysql type is varchar, default: "". In this case, the Scanner and Valuer interfaces can only be implemented manually?

**Comment by abice** [comment]
Do you mind expanding on the use case for an empty string enum value?

And if you need to implement a different sql/valuer interface methods, you can create a custom template and have the tool use that for your use case if the provided one doesn't do the right thing for you.

**Comment by Rain-JK** [comment]
I think "" maybe is useful for some table schema design like varchar, which is don't want to be null,

sometimes is easier for programing dont need deal with null

**Comment by emfadei** [comment]
You mean `ENUM(empty = "", value1)` ? 
Is is not parsed
failed parsing the data part of enum value 'empty = ""': strconv.ParseUint: parsing "\"\"": invalid syntax

**Comment by abice** [comment]
Thanks again for the interest in the project... I'm going to close this ticket now, but if you have troubles with it still... please either reopen or open a new ticket and I'll see what I can do to resolve it for you.

Thanks!

**Comment by nikki-dzhurov** [comment]
Hey @abice, I have very similar case - is there something similar for number-based enum types ? Probably what I want to achieve is kind of related to:  https://github.com/abice/go-enum/issues/207

Here is my example:
```
// ENUM(unset="", a,b,c).
type TestEnum uint8
```
