### ISSUE TITLE
Support interface for flag

### ISSUE THREAD

**Issue by tamalsaha** [abice/go-enum#13]
Thanks for this handy tool. Do you think it is reasonable to implement [the following interface](https://github.com/spf13/pflag/blob/1ce0cc6db4029d97571db82f85092fccedb572ce/flag.go#L187:6) so that it can be used as a Flag.

```
// Value is the interface to the dynamic value stored in a flag.
// (The default value is represented as a string.)
type Value interface {
	String() string
	Set(string) error
	Type() string
}
```

Currently I am manually implementing this.

**Comment by tamalsaha** [comment]
> Do you mean adding an option to have the generated enum implement that interface? Like how I have a flag for marshaling?

Yeah.

**Comment by abice** [comment]
Take a look at #14 and see if that fits the bill.

**Comment by tamalsaha** [comment]
Thanks @abice ! This looks great!
