### ISSUE TITLE
Problem using closing parentheses in enum values

### ISSUE THREAD

**Issue by sevein** [abice/go-enum#159]
For an enum like the following:

```go
// ENUM(
// Foo1 (X),
// Foo2 (Y),
// ).
type Example string
```

The generated code reads:

```go
const (
	// ExampleFoo1X is a Example of type Foo1 (X.
	ExampleFoo1X Example = "Foo1 (X"
	// ExampleFoo2Y is a Example of type Foo2 (Y.
	ExampleFoo2Y Example = "Foo2 (Y"
)
```

Could the issue be in that `trimAllTheThings` removes `)` and all subsequent characters?

**Comment by abice** [comment]
Hi @sevein, thanks for using the project and taking an interest!

I have to say that your use case is a bit odd to me. You actually want to have parentheses in the enum name/value?

Do you mind providing a little detail on what you might expect the enum generator to produce for various things? Spaces and parens are not something I've done before, personally, so I want to make sure I fully understand the desire before going and making changes.

Thanks again!

**Comment by sevein** [comment]
Thank you @abice! Yes, exactly. I'm actually trying to map an existing vocabulary that I'm not supposed to change.

I've adapted the example in the README:

```
// ENUM(pending, running, completed, completed (with warnings), failed)
type StrState string
```

I would expect the following:

```
const (
 // StrStatePending is a StrState of type pending.
 StrStatePending StrState = "pending"
 // StrStateRunning is a StrState of type running.
 StrStateRunning StrState = "running"
 // StrStateCompleted is a StrState of type completed.
 StrStateCompleted StrState = "completed"
 // StrStateCompleted is a StrState of type completed.
 StrStateCompletedWithWarnings StrState = "completed (with warnings)"
 // StrStateFailed is a StrState of type failed.
 StrStateFailed StrState = "failed"
)
```

Trimming parens like it's done already with spaces would be perfect. Not sure if that sounds reasonable. Otherwise I wonder if it'd be sensible to provide a way in the syntax to name the const identifiers manually.

**Comment by sevein** [comment]
@abice, just had an opportunity to test this. It's working great, thank you so much! :heart_eyes:
