### ISSUE TITLE
IsValid() method only generated for string types

### ISSUE THREAD

**Issue by twelvelabs** [abice/go-enum#177]
I recently changed one of my enums from `string` to `int` and discovered that the `.IsValid()` method was no longer available. It looks like it's only included in `enum_string.tmpl`:

https://github.com/abice/go-enum/blob/b9e7d1ac24b2b7f6a5b451fa3d21706ffd8d79e2/generator/enum_string.tmpl#L50C25-L53

Would you be open to a PR that added it to `enum.tmpl` as well?

**Comment by abice** [comment]
@twelvelabs Good catch!  I'm always open to a PR!  Otherwise, I'll make sure to pick this up next time I can.

Thanks for reporting!
