### ISSUE TITLE
NOTHING is working

### ISSUE THREAD

**Issue by khomin** [abice/go-enum#188]
curl -fsSL "https://github.com/abice/go-enum/releases/download/0.5.6/go-enum" -o go-enum

curl: (22) The requested URL returned error: 404

xxxx.go:1: running "go-enum": exec: "go-enum": executable file not found in $PATH

**Comment by abice** [comment]
Thanks for your interest in the project!

The actual command written in the readme is `curl -fsSL "https://github.com/abice/go-enum/releases/download/$(GO_ENUM_VERSION)/go-enum_$(uname -s)_$(uname -m)" -o go-enum`

This command has 3 sets of variables that will work on a linux system, but may need tweaking if you need to use it elsewhere.

If you want to just try things out, you can always download directly from github's release page, which has links to all the various build types that you may need: https://github.com/abice/go-enum/releases/tag/v0.5.6

You can also copy and paste those download links (like https://github.com/abice/go-enum/releases/download/v0.5.6/go-enum_Linux_x86_64)  into whatever curl command you'd like.

Thanks again for checking out the project, hope this gets you going with it!
