### ISSUE TITLE
linter unconvert (unnecessary conversion)

### ISSUE THREAD

**Issue by GhostRussia** [abice/go-enum#21]
`*_enum.go:38:23:warning: unnecessary conversion (unconvert)`

```
func ParseABC(name string) (ABC, error) {
	if x, ok := _ABCValue[name]; ok {
		return ABC(x), nil // <--
	}
	return ABC(0), fmt.Errorf("%s is not a valid ABC", name)
}
```

**Comment by abice** [comment]
Thanks for pointing that out!  I updated the template to remove that, and a few other linter warnings that were showing up.  Hope you're enjoying the project!
