### ISSUE TITLE
"--prefix" not worked

### ISSUE THREAD

**Issue by ghostiam** [abice/go-enum#38]
![Снимок экрана 2019-12-24 в 17 32 44](https://user-images.githubusercontent.com/12181586/71403545-66710980-2673-11ea-84fb-c7b3e74a6ffb.jpg)

**Comment by abice** [comment]
I never did finish implementing that feature, must have slipped past in one of my commits.  Is that a feature you'd like to see?

**Comment by ghostiam** [comment]
Not that it was vital, just a small note that the flag is inoperative.

**Comment by ghostiam** [comment]
@abice Thanks, but I assumed that this flag should replace the name from the type name.

At least I wanted to use this flag like this:
```go
//go:generate ../bin/go-enum -f=$GOFILE --prefix=AcmeInc

package example

// Products of AcmeInc ENUM(
// Anvil,
// Dynamite,
// Glue
// )
type MySuperDuperProduct int32
```

```go
const (
	AcmeIncAnvil MySuperDuperProduct = iota
	AcmeIncDynamite
	AcmeIncGlue
)
```

**Comment by abice** [comment]
You can use it in conjunction with --noprefix option to get that effect.
