### ISSUE TITLE
Unable to compile on Darwin

### ISSUE THREAD

**Issue by ConorNevin** [abice/go-enum#43]
```go
▶ go get github.com/abice/go-enum@v0.2.3
# github.com/Bowery/prompt
../../../Go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/ioctl_unix.go:25:28: undefined: unix.SYS_IOCTL
../../../Go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/ioctl_unix.go:38:28: undefined: unix.SYS_IOCTL
../../../Go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/ioctl_unix.go:55:28: undefined: unix.SYS_IOCTL
```

**Comment by ConorNevin** [comment]
@abice unfortunately it seems that the package this error stems from has been orphaned since the company that created it has shuttered.

How open would you be to moving to another cli library if I submitted the PR?

**Comment by abice** [comment]
@ConorNevin Thanks for reporting it... yeah, feel free to come up with a PR for changing the cli lib, I don't mind.  If you don't have a lot of time, then I can see about making time to get it fixed.
