### ISSUE TITLE
Comments should have punctuation

### ISSUE THREAD

**Issue by kroppt** [abice/go-enum#47]
### Problem

When each enum value is generated, it has a comment like so:
```go
// ColorBlack is a Color of type Black
// My personalized comment.
ColorBlack Color = iota
```

However, sometimes IDEs will concatenate comments together, so that when hovering over a symbol, you see the following:
```text
ColorBlack is a Color of type Black My personalized comment.
```

This is not a problem with the IDE.

The blog post [Godoc: documenting Go code](https://blog.golang.org/godoc) states:

> The convention is simple: to document a type, variable, constant, function, or even a package, write a regular comment directly preceding its declaration, with no intervening blank line.
> ```go
> // Fprint formats using the default formats for its operands and writes to w.
> ```
> Notice this comment is a complete sentence that begins with the name of the element it describes. This important convention allows us to generate documentation in a variety of formats, from plain text to HTML to UNIX man pages, and makes it read better when tools truncate it for brevity, such as when they extract the first line or sentence.

And the [Contribution Guide](https://golang.org/doc/contribute) states:

> Write in complete sentences with correct punctuation, just like for your comments in Go.

### Solution

The first line comment generated by go-enum should include punctuation.

The first example would become:
```go
// ColorBlack is a Color of type Black.
// My personalized comment.
ColorBlack Color = iota
```

And the IDE would show:
```text
ColorBlack is a Color of type Black. My personalized comment.
```

**Comment by abice** [comment]
Must have been an oversight, thanks for bringing it up.  Should be an easy one to take care of.
