### ISSUE TITLE
Question: How to support camel case format

### ISSUE THREAD

**Issue by godcong** [abice/go-enum#74]
How do I define ENUM to achieve this?

1. The text in name is in lower case
2. Int values in enumeration are case sensitive

```
const(
xxxDataSwap = iota
xxxBootNode
)

__Name="dataswapbootnode"
```

Also, can I ignore Parse's error like this:
```
ParseXXX(name)Type{
    //return a default value
}
```

**Comment by abice** [comment]
Can you elaborate on the reason for the text in the name being lowercase?  I'm not sure I understand the use case here.

I don't think I want to promote ignoring a parse error, but you're more than welcome to ignore it in any case you want (or add a custom template of your own that creates a method that doesn't do error checking)

**Comment by godcong** [comment]
I may use strings in the transmission of data.
Hopefully all lower case is just to make these strings a bit more regular and not to cause some errors due to case.
Otherwise I may need to be concerned about case errors when parsing.

**Comment by abice** [comment]
The tool already can parse items with case insensitivity, and when using snake case, it will convert the variable names to camel case. However, without the `_` to tell the tool where word breaks are, it can't create camel case variable names. The only thing I can think of would be to allow you to define the enums as camel cased and add a "force lower" flag of some sort... But I don't know how widespread that would be desired.  Any reason you can't do snake case for your transmitted enums?

Or, any reason you can't use a variable that is lowercase?

I'm not against adding something, but I'd like to explore other options before adding yet another flag to the CLI.

**Comment by godcong** [comment]
I think the reason for this is that these words are already defined in my database.

But I want to be able to slice and dice the words correctly, like this.
```
const(
   xxxBootNode
)
```

If I use CamelCase or camelCase I don't end up with the correct enum value.



Although I feel that if this is the case, I think it is acceptable
```
__Name="CamelCase"
```
But if it's in this format, I feel it looks a bit odd
```
__Name="camelCase"
```
Although, the final presentation is all about the following result
```
const(
xxxCamelCase = iota
)
```

**Comment by abice** [comment]
I was thinking about this a little bit more, and while I may not have time to update the code to add a flag right now, you can try using the `--alias` option to replace upper case values with lowercase variants to see if that does what you want.  

Define the enums as you want them serialized (i.e. lowercase) and then type out the alias you want them to look like.

`-a "bootnode:BootNode,camelcase:CamelCase"`. A _very_ hacky work around (and not nearly as maintainable as the point of the repo is about) right now, but will buy me some time to get a good option in place.

**Comment by abice** [comment]
@godcong try out the new version with the 'forcelower' flag and tell me if that hit the mark or not, thanks!

**Comment by godcong** [comment]
@abice yes,all was ok.
thanks.
